name: test_minpro_web_responsive
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_slidable: ^3.0.0
    
    #  flutter_web_plugins:
    #    sdk: flutter
        
  go_router: ^11.1.4
  intl: ^0.18.1
  provider: ^6.0.5
  tuple: ^2.0.2
  url_strategy: ^0.2.0

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
