name: test_minpro_web_responsive
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1
  provider: ^6.0.5
  tuple: ^2.0.2

dev_dependencies:

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
